export type PhotoChoice = {
	path: string;
	label: string;
	searchTags?: readonly string[];
	description?: string;
};

export type LetterSection = {
	key: string;
	paragraphs: readonly string[];
};

export type PhotoTrigger = {
	key: string;
	sectionKey: string;
	paragraphIndex: number;
	tokenIndex: number;
	image: string;
	imageLabel: string;
};

export const availablePhotos = [
	{
		path: "/listing/front-exterior.jpg",
		label: "Front exterior",
		searchTags: [
			"front",
			"exterior",
			"entry",
			"curb appeal",
			"garden",
			"porch",
			"plants"
		],
		description: "Front garden, exterior facade, and entry approach."
	},
	{
		path: "/listing/flexible-cottage.jpg",
		label: "Flexible cottage",
		searchTags: [
			"cottage",
			"guest house",
			"family",
			"in-law",
			"office",
			"back house",
			"flex space"
		],
		description: "Flexible back cottage for guests, family, office, or changing seasons of life."
	},
	{
		path: "/listing/workshop-office.jpg",
		label: "Workshop office",
		searchTags: [
			"workshop",
			"office",
			"work from home",
			"studio",
			"patio",
			"barn doors",
			"workspace"
		],
		description: "Workshop office with a work-from-home feel and patio connection."
	},
	{
		path: "/listing/evening-exterior.jpg",
		label: "Evening exterior",
		searchTags: [
			"evening",
			"exterior",
			"front",
			"street",
			"neighborhood",
			"light",
			"golden hour"
		],
		description: "Evening light on the exterior and quiet neighborhood setting."
	},
	{
		path: "/listing/backyard-retreat.jpg",
		label: "Backyard retreat",
		searchTags: [
			"backyard",
			"garden",
			"patio",
			"deck",
			"hot tub",
			"clawfoot tub",
			"plants",
			"trees",
			"retreat"
		],
		description: "Backyard retreat with greenery, patio life, trees, and relaxing tub moments."
	},
	{
		path: "/listing/front-rooms.jpg",
		label: "Front rooms",
		searchTags: [
			"interior",
			"front rooms",
			"living room",
			"dining",
			"bedroom",
			"light",
			"windows"
		],
		description: "Interior front rooms with warm natural light."
	},
	{
		path: "/listing/084-666-46th-street-89548-ptw-006-web.jpg",
		label: "084 666 46th Street 89548 Ptw 006 Web",
		searchTags: [
			"living",
			"dining",
			"common area",
			"interior",
			"light",
			"front rooms"
		],
		description: "Imported living, dining, or common area source photo."
	},
	{
		path: "/listing/092-666-46th-street-89548-ptw-014-web-3.jpg",
		label: "092 666 46th Street 89548 Ptw 014 Web",
		searchTags: [
			"outdoor",
			"backyard",
			"patio",
			"garden",
			"deck",
			"plants"
		],
		description: "Imported outdoor backyard or patio source photo."
	},
	{
		path: "/listing/001-666-46th-street-89548-p3k-001-web.jpg",
		label: "001 666 46th Street 89548 P3k 001 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms"
		],
		description: "Local source photo from Exterior Front Entry. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/090-666-46th-street-89548-ptw-012-web-3.jpg",
		label: "090 666 46th Street 89548 Ptw 012 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/057-666-46th-street-89548-p3k-057-web-2.jpg",
		label: "057 666 46th Street 89548 P3k 057 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/090-666-46th-street-89548-ptw-012-web-4.jpg",
		label: "090 666 46th Street 89548 Ptw 012 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/080-666-46th-street-89548-ptw-002-web-3.jpg",
		label: "080 666 46th Street 89548 Ptw 002 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/059-666-46th-street-89548-p3k-059-web-5.jpg",
		label: "059 666 46th Street 89548 P3k 059 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/076-666-46th-street-89548-p3k-076-web-2.jpg",
		label: "076 666 46th Street 89548 P3k 076 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/073-666-46th-street-89548-p3k-073-web.jpg",
		label: "073 666 46th Street 89548 P3k 073 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/075-666-46th-street-89548-p3k-075-web-2.jpg",
		label: "075 666 46th Street 89548 P3k 075 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/073-666-46th-street-89548-p3k-073-web-2.jpg",
		label: "073 666 46th Street 89548 P3k 073 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/054-666-46th-street-89548-p3k-054-web.jpg",
		label: "054 666 46th Street 89548 P3k 054 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/043-666-46th-street-89548-p3k-043-web-2.jpg",
		label: "043 666 46th Street 89548 P3k 043 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/041-666-46th-street-89548-p3k-041-web.jpg",
		label: "041 666 46th Street 89548 P3k 041 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/066-666-46th-street-89548-p3k-066-web.jpg",
		label: "066 666 46th Street 89548 P3k 066 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/064-666-46th-street-89548-p3k-064-web-2.jpg",
		label: "064 666 46th Street 89548 P3k 064 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/062-666-46th-street-89548-p3k-062-web.jpg",
		label: "062 666 46th Street 89548 P3k 062 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/077-666-46th-street-89548-p3k-077-web-2.jpg",
		label: "077 666 46th Street 89548 P3k 077 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/078-666-46th-street-89548-p3k-078-web-2.jpg",
		label: "078 666 46th Street 89548 P3k 078 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/078-666-46th-street-89548-p3k-078-web-3.jpg",
		label: "078 666 46th Street 89548 P3k 078 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/071-666-46th-street-89548-p3k-071-web-2.jpg",
		label: "071 666 46th Street 89548 P3k 071 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/072-666-46th-street-89548-p3k-072-web.jpg",
		label: "072 666 46th Street 89548 P3k 072 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/091-666-46th-street-89548-ptw-013-web-2.jpg",
		label: "091 666 46th Street 89548 Ptw 013 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/017-666-46th-street-89548-p3k-017-web.jpg",
		label: "017 666 46th Street 89548 P3k 017 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/011-666-46th-street-89548-p3k-011-web-2.jpg",
		label: "011 666 46th Street 89548 P3k 011 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/026-666-46th-street-89548-p3k-026-web.jpg",
		label: "026 666 46th Street 89548 P3k 026 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/074-666-46th-street-89548-p3k-074-web.jpg",
		label: "074 666 46th Street 89548 P3k 074 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/070-666-46th-street-89548-p3k-070-web-2.jpg",
		label: "070 666 46th Street 89548 P3k 070 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bath",
			"bathroom",
			"laundry",
			"tub",
			"clawfoot tub",
			"soak"
		],
		description: "Local source photo from Bathrooms Laundry. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/095-666-46th-street-89548-ptw-017-web-2.jpg",
		label: "095 666 46th Street 89548 Ptw 017 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/092-666-46th-street-89548-ptw-014-web-4.jpg",
		label: "092 666 46th Street 89548 Ptw 014 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/089-666-46th-street-89548-ptw-011-web.jpg",
		label: "089 666 46th Street 89548 Ptw 011 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/090-666-46th-street-89548-ptw-012-web-5.jpg",
		label: "090 666 46th Street 89548 Ptw 012 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/085-666-46th-street-89548-ptw-007-web.jpg",
		label: "085 666 46th Street 89548 Ptw 007 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/049-666-46th-street-89548-p3k-049-web.jpg",
		label: "049 666 46th Street 89548 P3k 049 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/046-666-46th-street-89548-p3k-046-web.jpg",
		label: "046 666 46th Street 89548 P3k 046 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/055-666-46th-street-89548-p3k-055-web.jpg",
		label: "055 666 46th Street 89548 P3k 055 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/082-666-46th-street-89548-ptw-004-web.jpg",
		label: "082 666 46th Street 89548 Ptw 004 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/033-666-46th-street-89548-p3k-033-web-2.jpg",
		label: "033 666 46th Street 89548 P3k 033 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/090-666-46th-street-89548-ptw-012-web-6.jpg",
		label: "090 666 46th Street 89548 Ptw 012 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/059-666-46th-street-89548-p3k-059-web-6.jpg",
		label: "059 666 46th Street 89548 P3k 059 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/059-666-46th-street-89548-p3k-059-web-7.jpg",
		label: "059 666 46th Street 89548 P3k 059 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/080-666-46th-street-89548-ptw-002-web-4.jpg",
		label: "080 666 46th Street 89548 Ptw 002 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/076-666-46th-street-89548-p3k-076-web-3.jpg",
		label: "076 666 46th Street 89548 P3k 076 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/072-666-46th-street-89548-p3k-072-web-2.jpg",
		label: "072 666 46th Street 89548 P3k 072 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/073-666-46th-street-89548-p3k-073-web-3.jpg",
		label: "073 666 46th Street 89548 P3k 073 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/057-666-46th-street-89548-p3k-057-web-3.jpg",
		label: "057 666 46th Street 89548 P3k 057 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/057-666-46th-street-89548-p3k-057-web-4.jpg",
		label: "057 666 46th Street 89548 P3k 057 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/056-666-46th-street-89548-p3k-056-web-3.jpg",
		label: "056 666 46th Street 89548 P3k 056 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/005-666-46th-street-89548-p3k-005-web.jpg",
		label: "005 666 46th Street 89548 P3k 005 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms"
		],
		description: "Local source photo from Exterior Front Entry. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/005-666-46th-street-89548-p3k-005-web-2.jpg",
		label: "005 666 46th Street 89548 P3k 005 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms"
		],
		description: "Local source photo from Exterior Front Entry. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/013-666-46th-street-89548-p3k-013-web.jpg",
		label: "013 666 46th Street 89548 P3k 013 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/059-666-46th-street-89548-p3k-059-web-8.jpg",
		label: "059 666 46th Street 89548 P3k 059 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/080-666-46th-street-89548-ptw-002-web-5.jpg",
		label: "080 666 46th Street 89548 Ptw 002 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/054-666-46th-street-89548-p3k-054-web-2.jpg",
		label: "054 666 46th Street 89548 P3k 054 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/057-666-46th-street-89548-p3k-057-web-5.jpg",
		label: "057 666 46th Street 89548 P3k 057 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"backyard",
			"outdoor",
			"patio",
			"deck",
			"plants",
			"hot tub",
			"yard",
			"retreat",
			"trees",
			"redwoods",
			"tub",
			"spa",
			"soak",
			"relax",
			"stars",
			"plant map",
			"landscape",
			"greenery",
			"flowers",
			"avocado",
			"lime",
			"figs",
			"barn doors"
		],
		description: "Local source photo from Outdoor Backyard Patio. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/010-666-46th-street-89548-p3k-010-web.jpg",
		label: "010 666 46th Street 89548 P3k 010 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"living",
			"dining",
			"interior",
			"light",
			"windows"
		],
		description: "Local source photo from Living Dining Common Areas. Tags are inferred from the folder path and filename."
	},
	{
		path: "/listing/034-666-46th-street-89548-p3k-034-web.jpg",
		label: "034 666 46th Street 89548 P3k 034 Web",
		searchTags: [
			"exterior",
			"outside",
			"front",
			"entry",
			"facade",
			"street",
			"porch",
			"curb appeal",
			"garden",
			"front rooms",
			"bedroom",
			"nursery",
			"guest room",
			"sleep",
			"interior",
			"light",
			"bed",
			"kid room"
		],
		description: "Local source photo from Bedrooms. Tags are inferred from the folder path and filename."
	}
] as const satisfies readonly PhotoChoice[];

export const letterSections = [
	{
		key: "arrival",
		paragraphs: [
			"We weren't looking in this neighborhood when we came to the open house. The lot size and the space pulled us in, but it was wandering past the main house, past the cottage, into the workshop, and sitting in the backyard when the thought just landed: I want to live here. It persisted through a second open house, and every year since."
		]
	},
	{
		key: "family",
		paragraphs: [
			"The house has taken care of us as we've taken care of it. We welcomed our daughter here and watched her nursery slowly turn into a kid's room. Grandma moved into the back cottage and became a daily part of our daughter's life, giving us the kind of setup you don't really plan for, but can't imagine without once you have it. The same flexibility works just as well for guests, a home office, or whatever season of life you're in."
		]
	},
	{
		key: "workshop",
		paragraphs: [
			"The workshop became a real office. Full days of focused work out there, barn doors open to the patio because the weather is so often perfect. On commute days, a walk to MacArthur BART puts you in downtown San Francisco 25 minutes later, no car needed. That easy access alone changed how we thought about living on this side of the Bay."
		]
	},
	{
		key: "neighborhood",
		paragraphs: [
			"The block itself is calm in a way that surprised us. No spillover from the commercial streets, just kids out front on weekends and the occasional neighbor stopping by. Telegraph is moments away, with coffee, groceries, dinner, and nightlife close at hand. Our weekends found their own rhythm: coffee with neighbors at Mellana's across the street, a walk to the farmer's market, long evenings in the backyard."
		]
	},
	{
		key: "backyard",
		paragraphs: [
			"The house itself is wonderful, and we’ve spent countless hours in the front rooms with the light pouring in. But the backyard is what made the property different. The clawfoot tub tucked under the avocado tree is the best way to relax after a long week, save for the hot tub under the stars. Figs in late summer, hummingbirds drawn to the orange jubilee blooms, Makrut lime for cooking, grapes running along the fence. The redwoods in Kevin's yard next door arch over everything. We hosted often, but we also spent a lot of evenings out there doing nothing, which is the better endorsement."
		]
	},
	{
		key: "goodbye",
		paragraphs: [
			"We're leaving for reasons that have nothing to do with the house. What we want most is for it to be someone's home again, to take care of you the way it's taken care of us. We hope it lands for you the first time you sit out back.",
			"— Jacob and Amelia"
		]
	}
] as const satisfies readonly LetterSection[];

export const photoTriggers = [
	{
		key: "arrival",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/057-666-46th-street-89548-p3k-057-web-5.jpg",
		imageLabel: "057 666 46th Street 89548 P3k 057 Web"
	},
	{
		key: "arrival-14-the",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 26,
		image: "/listing/090-666-46th-street-89548-ptw-012-web-6.jpg",
		imageLabel: "090 666 46th Street 89548 Ptw 012 Web"
	},
	{
		key: "arrival-27-past",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 52,
		image: "/listing/005-666-46th-street-89548-p3k-005-web-2.jpg",
		imageLabel: "005 666 46th Street 89548 P3k 005 Web"
	},
	{
		key: "arrival-31-past",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 60,
		image: "/listing/059-666-46th-street-89548-p3k-059-web-7.jpg",
		imageLabel: "059 666 46th Street 89548 P3k 059 Web"
	},
	{
		key: "arrival-34-into",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 66,
		image: "/listing/076-666-46th-street-89548-p3k-076-web-3.jpg",
		imageLabel: "076 666 46th Street 89548 P3k 076 Web"
	},
	{
		key: "arrival-38-sitting",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 74,
		image: "/listing/073-666-46th-street-89548-p3k-073-web-3.jpg",
		imageLabel: "073 666 46th Street 89548 P3k 073 Web"
	},
	{
		key: "arrival-52-it",
		sectionKey: "arrival",
		paragraphIndex: 0,
		tokenIndex: 102,
		image: "/listing/010-666-46th-street-89548-p3k-010-web.jpg",
		imageLabel: "010 666 46th Street 89548 P3k 010 Web"
	},
	{
		key: "arrival-17-the",
		sectionKey: "arrival",
		paragraphIndex: 1,
		tokenIndex: 26,
		image: "/listing/090-666-46th-street-89548-ptw-012-web-4.jpg",
		imageLabel: "090 666 46th Street 89548 Ptw 012 Web"
	},
	{
		key: "arrival-31-the",
		sectionKey: "arrival",
		paragraphIndex: 1,
		tokenIndex: 54,
		image: "/listing/080-666-46th-street-89548-ptw-002-web-3.jpg",
		imageLabel: "080 666 46th Street 89548 Ptw 002 Web"
	},
	{
		key: "arrival-34-past",
		sectionKey: "arrival",
		paragraphIndex: 1,
		tokenIndex: 60,
		image: "/listing/059-666-46th-street-89548-p3k-059-web-5.jpg",
		imageLabel: "059 666 46th Street 89548 P3k 059 Web"
	},
	{
		key: "arrival-37-into",
		sectionKey: "arrival",
		paragraphIndex: 1,
		tokenIndex: 66,
		image: "/listing/076-666-46th-street-89548-p3k-076-web-2.jpg",
		imageLabel: "076 666 46th Street 89548 P3k 076 Web"
	},
	{
		key: "arrival-41-sitting",
		sectionKey: "arrival",
		paragraphIndex: 1,
		tokenIndex: 74,
		image: "/listing/073-666-46th-street-89548-p3k-073-web-2.jpg",
		imageLabel: "073 666 46th Street 89548 P3k 073 Web"
	},
	{
		key: "family",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/054-666-46th-street-89548-p3k-054-web.jpg",
		imageLabel: "054 666 46th Street 89548 P3k 054 Web"
	},
	{
		key: "family-81-our",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 30,
		image: "/listing/043-666-46th-street-89548-p3k-043-web-2.jpg",
		imageLabel: "043 666 46th Street 89548 P3k 043 Web"
	},
	{
		key: "family-89-turn",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 46,
		image: "/listing/041-666-46th-street-89548-p3k-041-web.jpg",
		imageLabel: "041 666 46th Street 89548 P3k 041 Web"
	},
	{
		key: "family-95-moved",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 58,
		image: "/listing/066-666-46th-street-89548-p3k-066-web.jpg",
		imageLabel: "066 666 46th Street 89548 P3k 066 Web"
	},
	{
		key: "family-103-daily",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 74,
		image: "/listing/064-666-46th-street-89548-p3k-064-web-2.jpg",
		imageLabel: "064 666 46th Street 89548 P3k 064 Web"
	},
	{
		key: "family-128-the",
		sectionKey: "family",
		paragraphIndex: 0,
		tokenIndex: 124,
		image: "/listing/062-666-46th-street-89548-p3k-062-web.jpg",
		imageLabel: "062 666 46th Street 89548 P3k 062 Web"
	},
	{
		key: "workshop",
		sectionKey: "workshop",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/077-666-46th-street-89548-p3k-077-web-2.jpg",
		imageLabel: "077 666 46th Street 89548 P3k 077 Web"
	},
	{
		key: "workshop-160-barn",
		sectionKey: "workshop",
		paragraphIndex: 0,
		tokenIndex: 26,
		image: "/listing/078-666-46th-street-89548-p3k-078-web-3.jpg",
		imageLabel: "078 666 46th Street 89548 P3k 078 Web"
	},
	{
		key: "workshop-176-a",
		sectionKey: "workshop",
		paragraphIndex: 0,
		tokenIndex: 58,
		image: "/listing/071-666-46th-street-89548-p3k-071-web-2.jpg",
		imageLabel: "071 666 46th Street 89548 P3k 071 Web"
	},
	{
		key: "neighborhood",
		sectionKey: "neighborhood",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/082-666-46th-street-89548-ptw-004-web.jpg",
		imageLabel: "082 666 46th Street 89548 Ptw 004 Web"
	},
	{
		key: "neighborhood-238-telegraph",
		sectionKey: "neighborhood",
		paragraphIndex: 0,
		tokenIndex: 58,
		image: "/listing/034-666-46th-street-89548-p3k-034-web.jpg",
		imageLabel: "034 666 46th Street 89548 P3k 034 Web"
	},
	{
		key: "neighborhood-271-long",
		sectionKey: "neighborhood",
		paragraphIndex: 0,
		tokenIndex: 124,
		image: "/listing/091-666-46th-street-89548-ptw-013-web-2.jpg",
		imageLabel: "091 666 46th Street 89548 Ptw 013 Web"
	},
	{
		key: "backyard",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/017-666-46th-street-89548-p3k-017-web.jpg",
		imageLabel: "017 666 46th Street 89548 P3k 017 Web"
	},
	{
		key: "backyard-285-hours",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 18,
		image: "/listing/011-666-46th-street-89548-p3k-011-web-2.jpg",
		imageLabel: "011 666 46th Street 89548 P3k 011 Web"
	},
	{
		key: "backyard-291-the",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 30,
		image: "/listing/026-666-46th-street-89548-p3k-026-web.jpg",
		imageLabel: "026 666 46th Street 89548 P3k 026 Web"
	},
	{
		key: "backyard-296-the",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 40,
		image: "/listing/057-666-46th-street-89548-p3k-057-web-4.jpg",
		imageLabel: "057 666 46th Street 89548 P3k 057 Web"
	},
	{
		key: "backyard-304-the",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 56,
		image: "/listing/070-666-46th-street-89548-p3k-070-web-2.jpg",
		imageLabel: "070 666 46th Street 89548 P3k 070 Web"
	},
	{
		key: "backyard-322-save",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 92,
		image: "/listing/092-666-46th-street-89548-ptw-014-web-4.jpg",
		imageLabel: "092 666 46th Street 89548 Ptw 014 Web"
	},
	{
		key: "backyard-341-makrut",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 130,
		image: "/listing/089-666-46th-street-89548-ptw-011-web.jpg",
		imageLabel: "089 666 46th Street 89548 Ptw 011 Web"
	},
	{
		key: "backyard-360-we",
		sectionKey: "backyard",
		paragraphIndex: 0,
		tokenIndex: 168,
		image: "/listing/090-666-46th-street-89548-ptw-012-web-5.jpg",
		imageLabel: "090 666 46th Street 89548 Ptw 012 Web"
	},
	{
		key: "goodbye",
		sectionKey: "goodbye",
		paragraphIndex: 0,
		tokenIndex: 0,
		image: "/listing/085-666-46th-street-89548-ptw-007-web.jpg",
		imageLabel: "085 666 46th Street 89548 Ptw 007 Web"
	},
	{
		key: "goodbye-392-what",
		sectionKey: "goodbye",
		paragraphIndex: 0,
		tokenIndex: 24,
		image: "/listing/049-666-46th-street-89548-p3k-049-web.jpg",
		imageLabel: "049 666 46th Street 89548 P3k 049 Web"
	},
	{
		key: "goodbye-404-to",
		sectionKey: "goodbye",
		paragraphIndex: 0,
		tokenIndex: 48,
		image: "/listing/046-666-46th-street-89548-p3k-046-web.jpg",
		imageLabel: "046 666 46th Street 89548 P3k 046 Web"
	},
	{
		key: "goodbye-419-lands",
		sectionKey: "goodbye",
		paragraphIndex: 0,
		tokenIndex: 78,
		image: "/listing/056-666-46th-street-89548-p3k-056-web-3.jpg",
		imageLabel: "056 666 46th Street 89548 P3k 056 Web"
	}
] as const satisfies readonly PhotoTrigger[];

export type SectionKey = (typeof letterSections)[number]['key'];
export type PhotoTriggerKey = (typeof photoTriggers)[number]['key'];

export function splitReadableText(paragraph: string) {
	return paragraph.split(/(\s+)/).filter(Boolean);
}

export function isSectionKey(value: string | undefined): value is SectionKey {
	return letterSections.some((section) => section.key === value);
}

export function isPhotoTriggerKey(value: string | undefined): value is PhotoTriggerKey {
	return photoTriggers.some((trigger) => trigger.key === value);
}
